### ISSUE TITLE
Error while running ./LHF.py

### ISSUE THREAD

**Issue by simra-k** [blindfuzzy/LHF#15]
i get the following error, even though I have pip and psutil installed:
**Traceback (most recent call last):
  File "./LHF.py", line 6, in <module>
    from Modules import recon
  File "/root/LHF/Modules/recon.py", line 9, in <module>
    import psutil
ImportError: No module named psutil**
Also is this code compatible for kali 2020?

**Comment by negativepid** [comment]
I have the same two errors on Kali 2023.4... any suggestions?
